universe:
  type: ETF                # ETF | COIN | STOCK
  market: KS               # KS=코스피(국내 상장 ETF)
  exclude_keywords: ["레버리지","채권","커버드콜","인버스","선물","ETN"]
  min_avg_turnover: 500000000    # 최근 20일 평균 거래대금 최소치 (예: 5억 원)

regime:
  spx_ticker: "069500.KS"
  sma_days: 200

scanner:
  daily_jump_threshold: 3.0      # (구버전 키) fallback 용 — 없애지 말고 둬도 됩니다
  trend_sma_short: 50
  trend_sma_long: 200
  trend_sma20_slope_days: 20
  adx_window: 14
  mfi_window: 14
  vol_z_window: 20

  # ✅ 새 임계값 섹션 (이 값들이 우선 적용됩니다)
  thresholds:
    adx_min: 20
    mfi_min: 50
    mfi_max: 80
    volz_min: 1.0
    daily_jump_pct: 3.0   # % 단위 (예: 3.0이면 3%)

  sector_top_k: 5
  per_sector_cap: 2
  top_n: 10
  weight_scheme: "equal"         # equal | inv_vol
  rebalance: "W"                 # D|W|M


sell_rules:
  hard_exit_under_sma200: true
  soft_exit_under_sma50: true
  mdd_trailing_pct: 0.10         # 10% 트레일링 스탑
  weak_momentum_days: 20
  adx_soft_threshold: 15
  mfi_soft_threshold: 40
  vol_z_soft_threshold: -1.0

backtest:
  slippage_bps: 8                # 0.08%
  fee_bps: 5
  trade_frequency: "W"           # 체결 빈도: D|W|M
  benchmark_code: "379800"       # KODEX 미국S&P500

ui:
  theme: "light"
  refresh_sec: 60
  slack_webhook: ""              # 슬랙 Webhook URL (옵션)

notifications:
  channel: "telegram"
  telegram:
    bot_token: "8216278192:AAFLuiVI8hrWr86uV2zs9gMLrTcZdO9tGyk"
    chat_id: 7457035904
  report:
    top_n: 5
    min_abs_ret: 0.003   # 0.3%

adaptive:
  enabled: true
  regime_source: "069500.KS"     # 코스피200 ETF
  regime_lookback_days: 200
  # ATR/Close 비율이 이 이상이면 bull→neutral 강등 (선택)
  vol_downgrade_atr_pct: 0.03

  profiles:
    bull:
      scanner:
        daily_jump_threshold: 0.3     # 당일 점프 완화(%)   예: 0.3
        adx_window: 14
        mfi_window: 14
        vol_z_window: 20
        min_adx: 15
        mfi_low: 45
        mfi_high: 85
        min_volz: 0.5
      universe:
        min_avg_turnover: 0           # 유동성 완화
        top_n: 10

    neutral:
      scanner:
        daily_jump_threshold: 0.5
        min_adx: 20
        mfi_low: 45
        mfi_high: 80
        min_volz: 1.0
      universe:
        min_avg_turnover: 0
        top_n: 8

    bear:
      scanner:
        daily_jump_threshold: 0.8     # 더 보수적
        min_adx: 25
        mfi_low: 40
        mfi_high: 70
        min_volz: 1.5
      universe:
        min_avg_turnover: 0
        top_n: 5
