@"
scanner:
  daily_jump_threshold: 0.0
  adx_window: 14
  mfi_window: 14
  vol_z_window: 20
  min_adx: 0
  mfi_low: 0
  mfi_high: 100
  min_volz: -9
regime:
  use: true
  sma_days: 200
universe:
  min_avg_turnover: 0
  top_n: 10
"@ | Out-File -Encoding utf8 config_friend.yaml
