universe:
  type: ETF                # ETF | COIN | STOCK
  market: KS               # KS=코스피(국내 상장 ETF)
  exclude_keywords: ["레버리지","채권","커버드콜","인버스","선물","ETN"]
  min_avg_turnover: 500000000    # 최근 20일 평균 거래대금 최소치 (예: 5억 원)

regime:
  spx_ticker: "069500.KS"
  sma_days: 200

scanner:
  daily_jump_threshold: 3.0      # 당일 등락률 (%) 기준
  trend_sma_short: 50
  trend_sma_long: 200
  trend_sma20_slope_days: 20
  adx_window: 14
  mfi_window: 14
  vol_z_window: 20
  sector_top_k: 5                # ✅ 확정
  per_sector_cap: 2
  top_n: 10                      # ✅ 확정
  weight_scheme: "equal"         # equal | inv_vol
  rebalance: "W"                 # D|W|M (일/주/월)

sell_rules:
  hard_exit_under_sma200: true
  soft_exit_under_sma50: true
  mdd_trailing_pct: 0.10         # 10% 트레일링 스탑
  weak_momentum_days: 20
  adx_soft_threshold: 15
  mfi_soft_threshold: 40
  vol_z_soft_threshold: -1.0

backtest:
  slippage_bps: 8                # 0.08%
  fee_bps: 5
  trade_frequency: "W"           # 체결 빈도: D|W|M
  benchmark_code: "379800"       # KODEX 미국S&P500

ui:
  theme: "light"
  refresh_sec: 60
  slack_webhook: ""              # 슬랙 Webhook URL (옵션)

notifications:
  channel: "telegram"
  telegram:
    bot_token: "8216278192:AAFLuiVI8hrWr86uV2zs9gMLrTcZdO9tGyk"
    chat_id: 7457035904
