
import sys
import os
import json
import traceback
from pathlib import Path

# Add project root
BASE_DIR = Path(__file__).parent.parent
sys.path.append(str(BASE_DIR))

# Mock paths if needed?
# generate_manual_execution_record defines paths relative to its __file__.
# So we rely on existing files generated by previous test runs.
# Assuming reports/live/execution_prep/latest/execution_prep_latest.json exists.

try:
    from app.generate_manual_execution_record import generate_record, PREP_LATEST, TICKET_LATEST
    
    print(f"PREP PATH: {PREP_LATEST}")
    if PREP_LATEST.exists():
        print(f"PREP CONTENT (First 100): {PREP_LATEST.read_text(encoding='utf-8')[:100]}")
    else:
        print("PREP MISSING!")

    confirm_token = "TEST_TOKEN_123"
    items_data = {
        "confirm_token": confirm_token,
        "items": [
           {"ticker": "069500", "side": "BUY", "executed_qty": 10, "avg_price": 30000, "status": "EXECUTED"}
        ],
        "filled_at": "2026-02-13T12:00:00Z"
    }

    print("Calling generate_record...")
    generate_record(confirm_token, items_data)
    print("Success!")

except Exception:
    traceback.print_exc()
