#!/bin/bash
# =============================================================================
# KRX Alertor Modular - Print Cron Install Entry
# Phase C-P.42: Oracle Cloud Scheduler (Print Only - No Execution)
# =============================================================================
# ⚠️ PRINT-ONLY: 이 스크립트는 명령을 출력만 합니다. 실행하지 않습니다!
# =============================================================================

set -euo pipefail

# 프로젝트 경로 (실제 경로로 수정 필요)
PROJECT_PATH="/home/ubuntu/krx_hyungsoo"

echo ""
echo "###############################################"
echo "### PRINT-ONLY: DO NOT EXECUTE IN THIS PHASE ###"
echo "###############################################"
echo ""

echo "============================================"
echo " PREFLIGHT COMMANDS (출력만)"
echo "============================================"
echo ""
echo "# 1. Timezone 확인"
echo "timedatectl"
echo "date"
echo ""
echo "# 2. Python 확인"
echo "python3 --version"
echo "ls -la ${PROJECT_PATH}/.venv/"
echo ""
echo "# 3. 안전장치 확인"
echo "cat ${PROJECT_PATH}/state/real_sender_enable.json"
echo "cat ${PROJECT_PATH}/state/execution_gate.json"
echo "cat ${PROJECT_PATH}/state/emergency_stop.json"
echo ""

echo "============================================"
echo " INSTALL OPTIONS (출력만)"
echo "============================================"
echo ""

echo "--- Option 1: Server TZ = Asia/Seoul (KST) ---"
echo ""
echo "# crontab -e 실행 후 아래 내용 추가:"
echo "# KRX Ops Cycle - 매일 09:05 KST"
echo "5 9 * * * cd ${PROJECT_PATH} && ./deploy/run_ops_cycle.sh >> logs/ops_cycle.log 2>&1"
echo ""

echo "--- Option 2: Server TZ = UTC ---"
echo "# (09:05 KST = 00:05 UTC)"
echo ""
echo "# crontab -e 실행 후 아래 내용 추가:"
echo "# KRX Ops Cycle - 매일 00:05 UTC (= 09:05 KST)"
echo "5 0 * * * cd ${PROJECT_PATH} && ./deploy/run_ops_cycle.sh >> logs/ops_cycle.log 2>&1"
echo ""

echo "--- Option 3: TZ 강제 지정 (권장) ---"
echo ""
echo "# crontab -e 실행 후 아래 내용 추가:"
echo "TZ=Asia/Seoul"
echo "5 9 * * * cd ${PROJECT_PATH} && ./deploy/run_ops_cycle.sh >> logs/ops_cycle.log 2>&1"
echo ""

echo "============================================"
echo " P97/P98: WATCHER CRON ENTRIES (권장 전체)"
echo "============================================"
echo ""
echo "# ===== crontab 맨 위에 추가 ====="
echo "TZ=Asia/Seoul"
echo ""
echo "# ===== Log Rotate (기존 유지) ====="
echo "0 1 * * 0 cd ${PROJECT_PATH} && test -f logs/daily_ops.log && tail -n 5000 logs/daily_ops.log > logs/daily_ops.log.tmp && mv -f logs/daily_ops.log.tmp logs/daily_ops.log || true"
echo ""
echo "# ===== Daily Ops - 매일 09:05 KST ====="
echo "5 9 * * * cd ${PROJECT_PATH} && bash deploy/oci/daily_ops.sh >> logs/daily_ops.log 2>&1"
echo ""
echo "# ===== Watchers - 장중 5분 (평일 09:00-15:59) ====="
echo "*/5 9-15 * * 1-5 cd ${PROJECT_PATH} && bash deploy/oci/spike_watch.sh >> logs/spike_watch.log 2>&1"
echo "*/5 9-15 * * 1-5 cd ${PROJECT_PATH} && bash deploy/oci/holding_watch.sh >> logs/holding_watch.log 2>&1"
echo ""
echo "# ===== P98: Watchers - 장외 1시간마다 신선도 유지 (STALE_DATA 방지) ====="
echo "0 * * * * cd ${PROJECT_PATH} && bash deploy/oci/spike_watch.sh >> logs/spike_watch.log 2>&1"
echo "5 * * * * cd ${PROJECT_PATH} && bash deploy/oci/holding_watch.sh >> logs/holding_watch.log 2>&1"
echo ""
echo "# ===== Bootstrap - 재부팅 후 1회 갱신 (NOT_RUN_YET 방지) ====="
echo "@reboot sleep 60 && cd ${PROJECT_PATH} && bash deploy/oci/spike_watch.sh >> logs/spike_watch.log 2>&1"
echo "@reboot sleep 60 && cd ${PROJECT_PATH} && bash deploy/oci/holding_watch.sh >> logs/holding_watch.log 2>&1"
echo ""

echo "============================================"
echo " POST-INSTALL PROOF (출력만)"
echo "============================================"
echo ""
echo "# 1. cron 등록 확인"
echo "crontab -l | grep krx"
echo ""
echo "# 2. 최초 실행 후 결과 확인"
echo "cat ${PROJECT_PATH}/reports/ops/scheduler/latest/ops_run_latest.json | jq .overall_status"
echo ""
echo "# 3. Health 확인"
echo "curl http://127.0.0.1:8000/api/ops/health"
echo ""

echo "============================================"
echo " ROLLBACK COMMANDS (출력만)"
echo "============================================"
echo ""
echo "# cron 제거"
echo "crontab -e  # 해당 라인 삭제"
echo ""
echo "# 또는 전체 초기화 (주의!)"
echo "# crontab -r"
echo ""

echo "###############################################"
echo "### END OF PRINT-ONLY OUTPUT ###"
echo "###############################################"
