version: "3.8"

services:
  krx_scanner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: krx_scanner
    environment:
      - TZ=Asia/Seoul
      - KRX_ALERTOR_DB=sqlite:////app/data/krx_alertor.sqlite3
    volumes:
      # 코드 전체 (읽기전용도 가능하지만 sectors_map 자동생성 등을 위해 rw 권장)
      - ../:/app
      # 데이터/로그/리포트 저장 디렉터리 (NAS 공유폴더를 /app/data 로 마운트)
      - /volume1/krx/data:/app/data
    restart: unless-stopped
