#!/bin/bash
# deploy/pc/print_export_strategy_bundle_linux.sh
# Strategy Bundle 생성 가이드 출력 (Print-Only, 자동 실행 없음)
# Phase C-P.47

echo "========================================"
echo " Strategy Bundle Export Guide (Linux)"
echo " Phase C-P.47 - Print Only"
echo "========================================"
echo ""
echo "[1] 번들 생성 커맨드 (수동 실행 필요):"
echo ""
echo "    cd /path/to/krx_hyungsoo"
echo "    python -c \""
echo "import json"
echo "import hashlib"
echo "import uuid"
echo "import socket"
echo "import subprocess"
echo "from datetime import datetime"
echo "from pathlib import Path"
echo ""
echo "BASE_DIR = Path('.')"
echo ""
echo "# strategy 섹션 정의 (튜닝 결과 반영)"
echo "strategy = {"
echo "    'name': 'KRX_MOMENTUM_V1',"
echo "    'version': '1.0.0',"
echo "    'universe': ['069500', '229200', '114800'],"
echo "    'lookbacks': {'momentum_period': 20, 'volatility_period': 14},"
echo "    'rebalance_rule': {'frequency': 'DAILY', 'time_kst': '09:05'},"
echo "    'risk_limits': {'max_position_pct': 0.25, 'max_drawdown_pct': 0.15},"
echo "    'position_limits': {'max_positions': 4, 'min_cash_pct': 0.10},"
echo "    'decision_params': {'entry_threshold': 0.02, 'exit_threshold': -0.03, 'adx_filter_min': 20}"
echo "}"
echo ""
echo "# SHA256 계산"
echo "strategy_json = json.dumps(strategy, sort_keys=True, separators=(',', ':'), ensure_ascii=False)"
echo "payload_sha256 = hashlib.sha256(strategy_json.encode('utf-8')).hexdigest()"
echo ""
echo "# Git 정보"
echo "git_commit = subprocess.getoutput('git rev-parse --short HEAD')"
echo "git_branch = subprocess.getoutput('git rev-parse --abbrev-ref HEAD')"
echo "active_surface_sha256 = hashlib.sha256((BASE_DIR / 'docs/ops/active_surface.json').read_bytes()).hexdigest()"
echo ""
echo "bundle = {"
echo "    'schema': 'STRATEGY_BUNDLE_V1',"
echo "    'bundle_id': str(uuid.uuid4()),"
echo "    'created_at': datetime.now().isoformat(),"
echo "    'source': {"
echo "        'pc_host': socket.gethostname(),"
echo "        'git_commit': git_commit,"
echo "        'git_branch': git_branch,"
echo "        'active_surface_sha256': active_surface_sha256"
echo "    },"
echo "    'strategy': strategy,"
echo "    'compat': {'min_oci_version': '1.46', 'expected_python': '3.10+'},"
echo "    'evidence_refs': [],"
echo "    'integrity': {"
echo "        'payload_sha256': payload_sha256,"
echo "        'signed_by': 'PC_LOCAL',"
echo "        'signature': '',"
echo "        'algorithm': 'HMAC-SHA256'"
echo "    }"
echo "}"
echo ""
echo "# 저장"
echo "out_dir = BASE_DIR / 'state/strategy_bundle/latest'"
echo "out_dir.mkdir(parents=True, exist_ok=True)"
echo "out_path = out_dir / 'strategy_bundle_latest.json'"
echo "out_path.write_text(json.dumps(bundle, indent=2, ensure_ascii=False), encoding='utf-8')"
echo "print(f'Bundle saved to: {out_path}')"
echo "print(f'Bundle ID: {bundle[\"bundle_id\"]}')"
echo "\""
echo ""
echo "[2] 생성물 위치:"
echo "    state/strategy_bundle/latest/strategy_bundle_latest.json"
echo ""
echo "[3] OCI로 전달 방법 (권장: Git):"
echo "    git add state/strategy_bundle/"
echo "    git commit -m 'feat: strategy bundle update'"
echo "    git push origin main"
echo ""
echo "    # OCI 측에서:"
echo "    git pull origin main"
echo ""
echo "[4] 금지사항:"
echo "    - 번들에 시크릿/토큰/계정ID 절대 포함 금지"
echo "    - .env 값 포함 금지"
echo ""
echo "========================================"
echo " 이 스크립트는 가이드만 출력합니다."
echo " 실제 실행은 위 커맨드를 수동으로 입력하세요."
echo "========================================"
