# deploy/pc/print_export_strategy_bundle_windows.ps1
# Strategy Bundle 생성 가이드 출력 (Print-Only, 자동 실행 없음)
# Phase C-P.47

Write-Host "========================================"
Write-Host " Strategy Bundle Export Guide (Windows)"
Write-Host " Phase C-P.47 - Print Only"
Write-Host "========================================"
Write-Host ""
Write-Host "[1] 번들 생성 커맨드 (수동 실행 필요):"
Write-Host ""
Write-Host '    cd "E:\AI Study\krx_alertor_modular"'
Write-Host "    python -c @'"
Write-Host "import json"
Write-Host "import hashlib"
Write-Host "import uuid"
Write-Host "import socket"
Write-Host "import subprocess"
Write-Host "from datetime import datetime"
Write-Host "from pathlib import Path"
Write-Host ""
Write-Host "BASE_DIR = Path('.')"
Write-Host ""
Write-Host "# strategy 섹션 정의 (튜닝 결과 반영)"
Write-Host "strategy = {"
Write-Host "    'name': 'KRX_MOMENTUM_V1',"
Write-Host "    'version': '1.0.0',"
Write-Host "    'universe': ['069500', '229200', '114800'],"
Write-Host "    'lookbacks': {'momentum_period': 20, 'volatility_period': 14},"
Write-Host "    'rebalance_rule': {'frequency': 'DAILY', 'time_kst': '09:05'},"
Write-Host "    'risk_limits': {'max_position_pct': 0.25, 'max_drawdown_pct': 0.15},"
Write-Host "    'position_limits': {'max_positions': 4, 'min_cash_pct': 0.10},"
Write-Host "    'decision_params': {'entry_threshold': 0.02, 'exit_threshold': -0.03, 'adx_filter_min': 20}"
Write-Host "}"
Write-Host ""
Write-Host "# SHA256 계산"
Write-Host "strategy_json = json.dumps(strategy, sort_keys=True, separators=(',', ':'), ensure_ascii=False)"
Write-Host "payload_sha256 = hashlib.sha256(strategy_json.encode('utf-8')).hexdigest()"
Write-Host ""
Write-Host "# Git 정보"
Write-Host "git_commit = subprocess.getoutput('git rev-parse --short HEAD')"
Write-Host "git_branch = subprocess.getoutput('git rev-parse --abbrev-ref HEAD')"
Write-Host "active_surface_sha256 = hashlib.sha256((BASE_DIR / 'docs/ops/active_surface.json').read_bytes()).hexdigest()"
Write-Host ""
Write-Host "bundle = {"
Write-Host "    'schema': 'STRATEGY_BUNDLE_V1',"
Write-Host "    'bundle_id': str(uuid.uuid4()),"
Write-Host "    'created_at': datetime.now().isoformat(),"
Write-Host "    'source': {"
Write-Host "        'pc_host': socket.gethostname(),"
Write-Host "        'git_commit': git_commit,"
Write-Host "        'git_branch': git_branch,"
Write-Host "        'active_surface_sha256': active_surface_sha256"
Write-Host "    },"
Write-Host "    'strategy': strategy,"
Write-Host "    'compat': {'min_oci_version': '1.46', 'expected_python': '3.10+'},"
Write-Host "    'evidence_refs': [],"
Write-Host "    'integrity': {"
Write-Host "        'payload_sha256': payload_sha256,"
Write-Host "        'signed_by': 'PC_LOCAL',"
Write-Host "        'signature': '',"
Write-Host "        'algorithm': 'HMAC-SHA256'"
Write-Host "    }"
Write-Host "}"
Write-Host ""
Write-Host "# 저장"
Write-Host "out_dir = BASE_DIR / 'state/strategy_bundle/latest'"
Write-Host "out_dir.mkdir(parents=True, exist_ok=True)"
Write-Host "out_path = out_dir / 'strategy_bundle_latest.json'"
Write-Host "out_path.write_text(json.dumps(bundle, indent=2, ensure_ascii=False), encoding='utf-8')"
Write-Host "print(f'Bundle saved to: {out_path}')"
Write-Host "print(f'Bundle ID: {bundle[\"bundle_id\"]}')"
Write-Host "'@"
Write-Host ""
Write-Host "[2] 생성물 위치:"
Write-Host "    state\strategy_bundle\latest\strategy_bundle_latest.json"
Write-Host ""
Write-Host "[3] OCI로 전달 방법 (권장: Git):"
Write-Host "    git add state/strategy_bundle/"
Write-Host '    git commit -m "feat: strategy bundle update"'
Write-Host "    git push origin main"
Write-Host ""
Write-Host "    # OCI 측에서:"
Write-Host "    git pull origin main"
Write-Host ""
Write-Host "[4] 금지사항:"
Write-Host "    - 번들에 시크릿/토큰/계정ID 절대 포함 금지"
Write-Host "    - .env 값 포함 금지"
Write-Host ""
Write-Host "========================================"
Write-Host " 이 스크립트는 가이드만 출력합니다."
Write-Host " 실제 실행은 위 커맨드를 수동으로 입력하세요."
Write-Host "========================================"
