# -*- coding: utf-8 -*-
# config/config.yaml
# KRX Alertor 설정 파일

# 데이터 소스
data:
  cache_dir: "data/cache/ohlcv"
  db_path: "data/krx_alertor.db"
  providers:
    - pykrx
    - fdr
    - stooq
    - yfinance

# ETF 필터링
filtering:
  min_price: 1000
  min_volume_value: 300000000  # 3억원
  exclude_keywords:
    - "레버리지"
    - "인버스"
    - "선물"
    - "채권"
    - "커버드콜"

# 백테스트
backtest:
  initial_capital: 10000000  # 1천만원
  commission_rate: 0.00015   # 0.015%
  slippage_rate: 0.001       # 0.1%
  max_positions: 10
  rebalance_frequency: "monthly"  # daily, weekly, monthly

# 전략
strategy:
  # 신호 생성
  signals:
    ma_period: 20
    rsi_period: 14
    adx_threshold: 20.0
    
  # 리스크 관리
  risk:
    position_cap: 0.25              # 종목당 최대 25%
    portfolio_vol_target: 0.12      # 목표 변동성 12%
    max_drawdown_threshold: -0.15   # 최대 낙폭 -15%
    cooldown_days: 5                # 쿨다운 5일
    max_correlation: 0.7            # 최대 상관계수 0.7
    min_liquidity: 300000000        # 최소 거래대금 3억

# 스캔
scan:
  min_confidence: 0.6
  top_n: 10
  lookback_days: 60

# 로깅
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  console: true
  file: true
  log_dir: "logs"

# 알림 (향후 구현)
notification:
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
  slack:
    enabled: false
    webhook_url: ""

# 스케줄 (향후 구현)
schedule:
  data_update:
    enabled: false
    cron: "0 18 * * 1-5"  # 평일 18:00
  scan:
    enabled: false
    cron: "0 9 * * 1-5"   # 평일 09:00
