# config/data_sources.yaml
# [U-STEP] 자동 유니버스 빌더 설정
universe_builder:
  output:
    yfinance: data/universe/yf_universe.txt      # 스캐너/인덱서가 참조하는 기본 유니버스
    krx: data/universe/krx_universe.txt          # (옵션) KRX 전용 유니버스 (미사용시 유지만)
  sources:
    # 1) 라인 기반 정적 리스트들(주석/공백 허용)
    static_lists:
      - data/universe/static/watchlist_core.txt
      - data/universe/static/etf_growth.txt
      - data/universe/static/etf_dividend.txt
      # 필요 시 자유롭게 추가
    # 2) CSV 기반 소스(심볼 컬럼 지정 + 간단 필터)
    csv_sources:
      - path: data/universe/custom.csv
        symbol_col: symbol
        filters:
          include_if:
            - column: active
              equals: 1
          exclude_if:
            - column: delisted
              equals: 1
    # 3) (선택) 질의형 소스 — 현재는 훅/플레이스홀더. 캐시나 사전생성 파일 없으면 [SKIP].
    queries:
      - provider: krx
        market: KOSPI
        top_n_by_market_cap: 200
        cache_file: data/cache/krx_top200.txt   # 있으면 사용, 없으면 [SKIP]
      - provider: yahoo
        indices: ["^GSPC", "^NDX"]
        top_n_by_weight: 100
        cache_file: data/cache/yahoo_index_top.txt

  rules:
    # 정규화/클린 규칙
    uppercase: true
    strip_prefixes: ["KRX:", "YF:", "XSHE:", "XSHG:"]
    dedup: true
    # 블랙리스트(한 줄당 하나)
    blacklist: data/universe/blacklist.txt

  # (훗날 UI에서 조정할 변수들 — 일단 기본값만 보유, 빌더는 값만 보관)
  ui_defaults:
    recentN_default: 30
    recentN_options: [10, 20, 30, 60, 120]
    min_price_krw: 1000           # 필터는 현재 비활성(캐시 미연결). 보관만.
    min_avg_volume: 50000

# 기존 data_sources.* 항목들은 그대로 유지하세요(아래에 다른 섹션이 있다면 그대로 두십시오).
