# KRX Scanner 설정 (베스트에포트)
# - SPoT: data_sources.yaml 의 yf.universe_key 를 우선 사용
# - 폴백: data/universe/<universe_key>.txt (1줄 1티커)
scanner:
  universe:
    source: data_sources         # data_sources | file | inline
    universe_key: "yf_universe"  # data_sources.yaml 의 yf.universe_key 와 일치
    file_fallback: "data/universe/yf_universe.txt"
    inline: []                   # 필요 시 여기에 ["AAPL","MSFT"] 처럼 직접 기입

  threshold:
    abs_pct: 0.03                # 절대 변화율 3% 이상 시 신호

  output:
    csv: "data/output/scanner_latest.csv"   # 최근 스캔 결과 저장
    send_telegram: true                     # 텔레그램 알림 사용

  runtime:
    max_rows: 10000              # 안전장치(과도한 출력 방지)
    timeout_sec: 60              # 스캔 타임아웃(있다면 앱에서 사용)

  regime:
    sma_days: 20
    spx_ticker: "^GSPC"   # S&P500 지수 티커 (yfinance 기준). 필요시 다른 지수로 교체 가능.
