# 스캐너 설정 (친구 코드 구조 참고)
# 이동평균 기반 모멘텀 전략

strategy:
  name: "MAPS"  # Moving Average Position Score
  
  # 이동평균 설정
  ma_period: 60
  
  # 포트폴리오 설정
  portfolio_topn: 5
  
  # 교체 임계값
  replace_score_threshold: 10.0
  
  # RSI 과매수 감지
  rsi_period: 14
  overbought_threshold: 70
  
  # 쿨다운
  cooldown_days: 5

# 시장 레짐 설정
market_regime:
  # 주요 지수 모니터링
  indices:
    - symbol: "^KS11"
      name: "KOSPI"
      ma_period: 60
    - symbol: "^KQ11"
      name: "KOSDAQ"
      ma_period: 60
  
  # 위험 모드 시 투자 비중
  risk_off_equity_ratio: 0.5

# 필터 설정
filters:
  min_volume: 100000
  min_price: 1000
  max_price: 1000000
  
  # 카테고리 중복 방지
  category_limit: 1

# 알림 설정
notification:
  telegram:
    enabled: false
    chat_id: ""
    token: ""
  
  slack:
    enabled: false
    webhook_url: ""
