# KRX Scanner 설정 (베스트에포트)
# - SPoT: data_sources.yaml 의 yf.universe_key 를 우선 사용
# - 폴백: data/universe/<universe_key>.txt (1줄 1티커)
scanner:
  universe:
    source: data_sources         # data_sources | file | inline
    universe_key: "yf_universe"  # data_sources.yaml 의 yf.universe_key 와 일치
    file_fallback: "data/universe/yf_universe.txt"
    inline: []

  threshold:
    abs_pct: 0.010                # 절대 변화율 3% 이상 시 신호

  output:
    csv: "data/output/scanner_latest.csv"   # 최근 스캔 결과 저장
    send_telegram: true                     # 텔레그램 알림 사용

  runtime:
    max_rows: 10000              # 안전장치(과도한 출력 방지)
    timeout_sec: 60              # 스캔 타임아웃(있다면 앱에서 사용)

  regime:
    sma_days: 20
    spx_ticker: "^KS11"      # S&P500 대신 KOSPI 지수로 전환(429 회피 목적)

  adx_window: 14     # 스캐너가 요구하는 ADX 윈도우, 일반적으로 14 사용